from operations import *

url_patterns = [
    ('/', login_page),
    ('/loading', loading_page),
    ('/loading_admin', loading_admin_page),
    ('/home', home_page),
    ('/admin', admin_page),
    ('/admin/users', users_page),
    ('/admin/timetable', timetable_page),
    ('/admin/conversation', conversation_page),
    ('/admin/event', event_page),
    ('/admin/lecturer', lecturer_page),
    ('/admin/lecturer/add_lecturer', add_lecturer_page),
    ('/admin/event/add_event', add_event_page),
    ('/admin/timetable/add_timetable', add_timetable_page),
    ('/signup', signup_page),
    ('/forgot_password', forgot_password_page),
    ('/loading_recovery', loading_recovery_page),
    ('/recovery', recovery_page),
    ('/loading_reset', loading_reset_page),
    ('/reset_password', reset_password_page),
    ('/loading_login', loading_login_page),
    ('/change_password', change_password_page),
    ('/chat', chat_page),
    ('/loading_chat', loading_chat_page),
    ('/profile', profile_page),
    ('/logout', logout),
    ('loading_logout', loading_logout),
    ('/front_end/root.css', root_css),
    ('/front_end/login.css', login_css),
    ('/front_end/signup.css', signup_css),
    ('/front_end/admin.css', admin_css),
    ('/front_end/root.js', root_js),
    ('/front_end/signup.js', signup_js),
    ('/front_end/admin.js', admin_js),
]
